apiVersion: v1
kind: Service
metadata:
  name: exoplanets-api-service
spec:
  type: NodePort
  selector:
    app: exoplanets-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31378  # Optional, Kubernetes can assign one if not specified
