name: Pull Request Validation

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

concurrency:
  group: validate-pr
  cancel-in-progress: true

jobs:
  validate-pr:
    if: ${{ github.event.pull_request.draft == false }}
    uses: ./.github/workflows/test-swift.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}